def show_menu():
    print("="*40)
    print("\tShelfLife V2")
    print("Terminal Inventory Management System")
    print("="*40)
    print("1. Add Product")
    print("2. View Product")
    print("3. Search Product")
    print("4. Update Quantity")
    print("5. Remove Product\n")
    print("----- Reports -----")
    print("6. Check Low Stock Products")
    print("7. Expiry Report\n")
    print("----- Import/Export -----")
    print("8. Export to JSON")
    print("9. Import from JSON")
    print("10. Export from CSV")
    print("11. Import from CSV\n")
    print("---- Functionalities------")
    print("12. Inventory Statistics")
    print("13. Sort Products")
    print("0. Exit!")